import { Product, Order } from './types'

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Cuffie Wireless Over-Ear Noise Cancelling Pro',
    brand: 'SoundCore',
    price: 219.90,
    originalPrice: 319.90,
    rating: 4.6,
    reviewCount: 8421,
    category: 'Audio',
    discount: 31,
    inStock: true,
    imageUrl: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&q=80',
    features: [
      'Driver 40mm con membrana al titanio per bassi profondi',
      'Cancellazione attiva del rumore di nuova generazione',
      'Autonomia fino a 35 ore con singola ricarica USB-C',
      'Connessione multipoint simultanea a 2 dispositivi',
      'Ricarica rapida: 5 min = 2 ore di ascolto',
      'Pieghevole con custodia rigida in dotazione',
    ],
    specs: {
      Marca: 'SoundCore',
      Categoria: 'Audio',
      Garanzia: '24 mesi',
      Connettività: 'Bluetooth 5.3, USB-C',
      Peso: '285g',
      Colore: 'Space Black',
      Modello: '2025',
      Certificazioni: 'CE, RoHS',
    },
  },
  {
    id: 2,
    name: 'Smartphone 6.7" AMOLED 200MP 512GB Titanio',
    brand: 'NovaTech',
    price: 899.00,
    originalPrice: 1049.00,
    rating: 4.4,
    reviewCount: 2130,
    category: 'Smartphone',
    discount: 14,
    inStock: true,
    imageUrl: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&q=80',
    features: [
      'Display AMOLED 6.7" 120Hz adattivo',
      'Tripla fotocamera 200MP con zoom 100x',
      'Processore Octa-core 4nm di nuova generazione',
      'Batteria 5000mAh con ricarica 65W wireless',
      'RAM 12GB LPDDR5X + 512GB UFS 4.0',
      'Resistenza IP68 acqua e polvere',
    ],
    specs: {
      Marca: 'NovaTech',
      Display: '6.7" AMOLED 120Hz',
      Processore: 'Octa-core 4nm',
      RAM: '12GB',
      Storage: '512GB',
      Batteria: '5000mAh',
      Certificazioni: 'IP68, CE',
      Garanzia: '24 mesi',
    },
  },
  {
    id: 3,
    name: 'Laptop Ultrabook 14" 16GB RAM 1TB SSD',
    brand: 'SwiftBook',
    price: 1199.00,
    originalPrice: 1399.00,
    rating: 4.8,
    reviewCount: 5670,
    category: 'Informatica',
    discount: 14,
    inStock: true,
    imageUrl: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=600&q=80',
    features: [
      'Processore M-Chip 10-core ad alte prestazioni',
      'Display Retina 14" 2560x1664 ProMotion 120Hz',
      '16GB RAM unificata + 1TB SSD NVMe',
      'Autonomia fino a 18 ore di utilizzo reale',
      'Ricarica MagSafe 96W inclusa',
      'Scocca in alluminio riciclato certificato',
    ],
    specs: {
      Processore: 'M-Chip 10-core',
      RAM: '16GB unificata',
      Storage: '1TB SSD',
      Display: '14" Retina 120Hz',
      Autonomia: '18 ore',
      Peso: '1.61 kg',
      Porte: 'USB-C x3, MagSafe, Jack 3.5mm',
      Garanzia: '12 mesi',
    },
  },
  {
    id: 4,
    name: 'Monitor 4K 27" IPS 144Hz HDR USB-C',
    brand: 'ClearView',
    price: 449.00,
    originalPrice: 599.00,
    rating: 4.5,
    reviewCount: 3210,
    category: 'Monitor',
    discount: 25,
    inStock: true,
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f4834c?w=600&q=80',
    features: [
      'Pannello IPS 4K 3840x2160 a 144Hz',
      'HDR600 con 600 nit di picco luminoso',
      'USB-C 90W Power Delivery integrato',
      'Delta E < 1 con copertura 99% sRGB',
      'Regolazione altezza, inclinazione e rotazione',
      'KVM integrato per gestire 2 PC simultaneamente',
    ],
    specs: {
      Risoluzione: '3840x2160 (4K)',
      'Refresh Rate': '144Hz',
      Pannello: 'IPS',
      HDR: 'HDR600',
      'USB-C': '90W Power Delivery',
      'Dimensioni': '27"',
      Garanzia: '36 mesi',
      Peso: '6.2 kg',
    },
  },
  {
    id: 5,
    name: 'Smartwatch GPS AMOLED 7 giorni autonomia',
    brand: 'PulseWear',
    price: 289.00,
    originalPrice: 369.00,
    rating: 4.3,
    reviewCount: 1890,
    category: 'Wearable',
    discount: 22,
    inStock: false,
    imageUrl: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80',
    features: [
      'Display AMOLED Always-On 1.43"',
      'GPS dual-band ad alta precisione',
      'Monitoraggio SpO2, ECG e stress continuo',
      '150+ modalità sportive con analisi avanzata',
      'Impermeabile fino a 5ATM',
      'Compatibile iOS e Android',
    ],
    specs: {
      Display: '1.43" AMOLED AOD',
      GPS: 'Dual-band L1+L5',
      Autonomia: '7 giorni GPS attivo',
      Impermeabilità: '5ATM',
      Sensori: 'SpO2, ECG, Temperatura',
      Compatibilità: 'iOS 14+ / Android 8+',
      Garanzia: '24 mesi',
      Peso: '45g',
    },
  },
  {
    id: 6,
    name: 'Fotocamera Mirrorless Full-Frame 61MP + 28-70mm',
    brand: 'OpticLens',
    price: 2299.00,
    originalPrice: 2799.00,
    rating: 4.9,
    reviewCount: 987,
    category: 'Fotografia',
    discount: 18,
    inStock: true,
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&q=80',
    features: [
      'Sensore Full-Frame BSI CMOS 61 Megapixel',
      'Stabilizzazione ottica 5.5 stop in-body',
      'Raffica 10fps con AF/AE continuo',
      'Video 4K 60fps 10-bit S-Log3',
      'Doppio slot SD UHS-II',
      'Corpo tropicalizzato IP54',
    ],
    specs: {
      Sensore: 'Full-Frame BSI CMOS 61MP',
      Stabilizzazione: '5.5 stop IBIS',
      Raffica: '10fps RAW',
      Video: '4K 60fps 10-bit',
      Mirino: 'EVF 0.5" 9.44M dot',
      Batteria: 'NP-FZ100 ~500 scatti',
      Garanzia: '24 mesi',
      Peso: '737g (con batteria)',
    },
  },
]

export const ORDERS: Order[] = [
  {
    id: 'TS-2025-00841',
    date: '28 Apr 2025',
    status: 'Consegnato',
    items: [PRODUCTS[0]],
    total: 219.90,
    trackingCode: 'GLS12345IT',
  },
  {
    id: 'TS-2025-00712',
    date: '15 Apr 2025',
    status: 'In transito',
    items: [PRODUCTS[2], PRODUCTS[3]],
    total: 1648.00,
    trackingCode: 'BRT98765IT',
  },
  {
    id: 'TS-2025-00601',
    date: '02 Apr 2025',
    status: 'Reso avviato',
    items: [PRODUCTS[4]],
    total: 289.00,
  },
  {
    id: 'TS-2025-00488',
    date: '10 Mar 2025',
    status: 'Consegnato',
    items: [PRODUCTS[1]],
    total: 899.00,
    trackingCode: 'GLS54321IT',
  },
]

export const NAV_CATEGORIES = [
  'Elettronica', 'Informatica', 'Audio & Video',
  'Smart Home', 'Fotografia', 'Gaming', 'Wearable', 'Accessori',
]

export const QUICK_CATEGORIES = [
  { icon: '📱', label: 'Phone' },
  { icon: '💻', label: 'Laptop' },
  { icon: '🎧', label: 'Audio' },
  { icon: '📷', label: 'Foto' },
  { icon: '🕹️', label: 'Gaming' },
  { icon: '⌚', label: 'Watch' },
  { icon: '🏠', label: 'Smart Home' },
  { icon: '🖱️', label: 'Altro' },
]
